sudo: required
services:
  - docker

before_install:
  - docker build -t hf1979/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hf1979/client-test npm test

after_success:
  - docker build -t w3devr/complex-client ./client
  - docker build -t w3devr/complex-nginx ./nginx
  - docker build -t w3devr/complex-server ./server
  - docker build -t w3devr/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push w3devr/complex-client
  - docker push w3devr/complex-nginx
  - docker push w3devr/complex-server
  - docker push w3devr/complex-worker