sudo: required
services:
  - docker

before_install:
  - docker build -t hf1979/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hf1979/client-test npm test

after_success:
  - docker build -t w3devr/complex-client ./client
  - docker build -t w3devr/complex-nginx ./nginx
  - docker build -t w3devr/complex-server ./server
  - docker build -t w3devr/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push w3devr/complex-client
  - docker push w3devr/complex-nginx
  - docker push w3devr/complex-server
  - docker push w3devr/complex-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "complex-app"
  env: "Complexapp-env"
  bucket_name: "elasticbeanstalk-eu-west-3-224725123617"
  bucket_path: "docker-complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY